
#SPSA: optimization method - only needs 2 curcuit evaluations per step (regaurdless of how many parameters theta has)

import numpy as np

# knobs -- a is how big a step we take, c is how far we peek in each direction
LEARNING_RATE = 0.01
SPSA_PERTURBATION = 0.1
MAX_ITERS = 100


def spsa_step (theta, loss_fn, a:float = LEARNING_RATE, c:float = SPSA_PERTURBATION):
#SPSA - it wil nudge every parameter randomlly, check if it helped, then step in whichever direction is closer

    delta = np.random.choice([-1,1], size = len(theta)) #a coin flip for every parameter (+1 means nudge it up and -1 meeans nudge it down)

    loss_plus = loss_fn (theta + c * delta) #move in the direction "delta" points and check the errorr
    loss_minus = loss_fn (theta - c * delta) #move in the OPPOSITE direction "delta" points and check the error

    gradient_estimate = (loss_plus - loss_minus) / (2 * c) * delta #compares the two errors to guess which way is downhill for each parameter at once
    
    return theta - a * gradient_estimate #take a step down (baased on learning rate "a")

def parameter_shift_gradient(theta, loss_fn, shift: float = np.pi / 2):
#parameter shift rule for a gate generated by a pauli operater - causes 2 theta evaluations 

    grad = np.zeros_like(theta) #

    for i in range(len(theta)): #checks each parameter separatly 
        shifted = theta.copy() #makes a new copy (doesnt mess up the original)

        shifted[i] += shift #bump this one parameter up
        loss_plus = loss_fn(shifted) #check error

        shifted[i] -= 2 * shift #bump the same parameter down
        loss_minus = loss_fn(shifted) #check error

        grad [i] = (loss_plus - loss_minus) #calculated difference and ditermines which way to move 

    return grad 

def gradient_descent_step(theta, gradient, learning_rate: float = LEARNING_RATE):
#we which way to move (gradient) - now we just take a small step that way 
    return theta - learning_rate * gradient 

def train(theta_init, loss_fn, method: str = "spsa", max_iters: int = MAX_ITERS):
#runs the classical optimization loop (spsa)
#cobyla is like a baseline
   
    theta = np.array(theta_init, dtype=float) #start form the first guess of the parameters 

    #lets scipy's optimizer handle everything and just return its answer
    if method == "cobyla":
        from scipy.optimize import minimize
        result = minimize (loss_fn, theta, method="COBYLA", options={"maxiter": max_iters})
        return result.x, [result.fun]
    
    history = [] #keeps track of the error after every step 
 
    for _ in range(max_iters): #update the process for max_iters amount of times
        if method == "spsa":
            theta = spsa_step(theta, loss_fn) #update using the random nudge method

        elif method == "parameter shift":
            grad = parameter_shift_gradient(theta, loss_fn) #find exact direction
            theta = gradient_descent_step(theta, grad) #takes a step in that direction 

        else:
            raise ValueError(f"Unknown method: {method}") #will fail if the method name is wrong

        history.append(loss_fn(theta)) #write current error before looping agian

    return theta, history #gives the final trained parameters and the error history 


